### ISSUE TITLE
Can't type ⍁

### ISSUE THREAD

**Issue by GolfingSuccess** [ngn/apl#101]
Typing `ff⍟/⍟` where `⍟` represents a tab doesn't seem to result into `⍁`. Instead, typing `[/⍟` works, but is undocumented (just like many other key combinations which aren't on the top bar).

**Comment by ngn** [comment]
When I move the cursor over `⍁` in the language bar, I get this tooltip:
![a](https://user-images.githubusercontent.com/188463/33041239-53b23288-ce46-11e7-8650-a5c05556ec0a.png)
Don't you?

**Comment by GolfingSuccess** [comment]
@ngn No, I don't. I get an upstile instead of a `[` (although that might be my browser cropping a bit at the bottom).
