### ISSUE TITLE
unexpected INDEX ERROR

### ISSUE THREAD

**Issue by MareinK** [ngn/apl#102]
I tried to run the code from [here](https://codegolf.stackexchange.com/a/6677), however the program gives 'INDEX ERROR'. The code given in the link is valid since it works [here](http://tryapl.org/index.dyalog).

**Comment by ngn** [comment]
This is because array indices in Dyalog start from 1 by default (that can be changed with `⎕io←0`). In ngn/apl they start strictly from 0.

**Comment by MareinK** [comment]
I see, thanks!
