### ISSUE TITLE
Comparison Tolerance is 0

### ISSUE THREAD

**Issue by plj541** [ngn/apl#42]
I'm concerned that I may have mislead people by expressing my personal experience.  While I've never worked on a problem where ⎕CT was critical, its presence in APL systems is essentially universal.

I've seen Ken respond to mathematicians who express concern about
   A=B and B=C  does not imply A=C
"No carpenter would ever cut lumber assuming that was true."

While I support leaving it out for now, it needs more of a comment than you can write your own replacement for equal.  Several APL functions are ⎕CT sensitive, and most APL users are unlikely to know how to write their own. I've converted the following from Paul Berry's 1979 manual.  I believe there are other functions which need examples, but I'm offering these now to help explain to users what is needed.

...
⍃← 1e¯14        ⍝ A name your unlikely to use
get_CT← {⍃}
set_CT← {
 0= ≡⍵ : ⎕← 'RANK ERROR setting CT'
 ⍵> 1e¯10 : ⎕← 'DOMAIN ERROR setting CT'
 ⍃← ⍵
}

EQ← {(|⍺-⍵)≤ CT× (|⍺)⌈ ∣⍵}
NE← {~⍺ EQ ⍵}
LT← {(⍺< ⍵)∧ ~⍺ EQ ⍵}
LE← {(⍺≤ ⍵)∨  ⍺ EQ ⍵}
GE← {(⍺≥ ⍵)∨  ⍺ EQ ⍵}
GT← {(⍺> ⍵)∧ ~⍺ EQ ⍵}

FLOOR← {
 Nearest← (×⍵)× ⌊0.5+⍵
 ⍝         Error        Permissible
 Nearest- (Nearest- ⍵)> CT× 1⌈ |⍵
}

CEILING← {
 -CT FLOOR -⍵
}
...

**Comment by ngn** [comment]
I'm closing this issue.  My views haven't changed in the past two years.  I think the transitivity problem defeats any argument for `⎕CT`.
