### ISSUE TITLE
Unexpected output in a 2-train

### ISSUE THREAD

**Issue by ararslan** [ngn/apl#90]
It seems that the train `÷-` doesn't yield the expected result (at least in comparison to Dyalog).

As an example, consider `(÷-)3`. In Dyalog, this returns -0.3333 since it applies monadic - to 3 to get -3, then monadic ÷ to -3 to get -1/3. As I understand it, the evaluation for 2-trains should be `(f g)(x) = f(g(x))`. However, in ngn/apl this returns -1 and I'm not really sure why.

Is this an expected/planned difference between Dyalog and ngn/apl?

**Comment by ngn** [comment]
Here's the story.  The idea for trains came from J: http://www.jsoftware.com/help/learning/09.htm
Dyalog adopted it with one modification -- the 2-train is an _atop_ instead of a _hook_
http://help.dyalog.com/14.1/Content/Language/Introduction/Trains.htm
Note the difference when they are applied monadically:
```
(f g)A  ←→  A f (g A)      hook in J
(f g)A  ←→    f (g A)      atop in Dyalog
```
At the time I added trains to this project I was unaware of Dyalog's decision, so I implemented hooks.  I don't have a strong opinion one way or the other.  Do you think it's better to switch to atops?

**Comment by ararslan** [comment]
Thanks for the explanation, I appreciate it! I'd probably say that atops would be a good way to go to maintain compatibility with Dyalog, but I don't know how much compatibility with Dyalog you care about for this project.

**Comment by ngn** [comment]
Note that `f∘g` is not exactly equivalent to the atop `(f g)` in the dyadic case, for instance:
```
A f∘g B  ←→  A f g B
A(f g)B  ←→  f A g B
```
As for compatibility with Dyalog or anything else, my policy is not to have a policy :)  This is a fun, experimental project.  However, I am of the conviction that users should have power over the language -- an alien concept in the world of APL where only the interpreter developer gods can mess with the notation.  So, in ngn/apl I added this file `prelude.apl` that gets sourced before any code is executed.  It contains the [definition of hook as if it's an operator](https://github.com/ngn/apl/blob/0ef93438307d1c70a11dc6e91f092b70cfbd2530/src/prelude.apl#L25) (in case you're wondering: `{A;B}` means monadic case `A` and dyadic case `B`.  The underlined `⍶` and `⍹` mean the same as `⍺⍺` and `⍵⍵`).  Internally `(f g)` compiles to `f _hook g`.  I think I'll switch to atops at some point but even before I do, it's possible for you to experiment with them by [redefining `_hook`](http://ngn.github.io/apl/web/index.html#code=_hook%u2190%7B%u2376%u2379%u2375%3B%u2376%u237A%u2379%u2375%7D%20%u235D%20change%20it%20to%20atop%0Af%u2190%7B%27%28f%27%u2375%27%29%27%20%3B%20%27%28%27%u237A%27f%27%u2375%27%29%27%7D%0Ag%u2190%7B%27%28g%27%u2375%27%29%27%20%3B%20%27%28%27%u237A%27g%27%u2375%27%29%27%7D%0A1%28f%20g%292).
