### ISSUE TITLE
Square root of negative 4 looks wrong

### ISSUE THREAD

**Issue by plj541** [ngn/apl#94]
I'm no expert on complex numbers, but the following looks wrong.
    a←¯4*0.5
1.2246467991473532e¯16j2

Other APL implementations yield 0j2.  There may be lots of other wrong roots.

**Comment by ngn** [comment]
This is due to error accumulated from the formula `pow(x,y)=exp(y*ln(x))`.
`1.224e¯16` is pretty close to `0`.  It's inevitable that some roots be wrong.
I'll add 0.5 as a special case because of its significance.
