### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by louisvangeldrop** [ngn/apl#95]
I am using Visual Studio Code as a development environment. My question: is it possible to include the APL-transpiler as an extension to Visual Studio Code?

**Comment by ngn** [comment]
Yes, if there are people willing to do this.  The [licence](https://github.com/ngn/apl/blob/master/licence) doesn't forbid it.

**Comment by louisvangeldrop** [comment]
Actually I don't have the knowledge how to achieve this. I do know APL and I used/loved the language since 1973. The availability of the APL-language transpiler within a generic tool as VSC could spread the usage of APL across the Javascript community. It was just a suggestion of a my side in order to be able to use APL in a Javascript environment.

**Comment by ngn** [comment]
I'm afraid I don't know much about VSC either.  I do all my programming in vim.
I think, for the popularization of APL, integration with VSC is unlikely to buy us as great a mindshare as you may think.  JavaScript is a hugely popular language these days, with developers coming from different backgrounds and using a variety of tools to edit code.

**Comment by louisvangeldrop** [comment]
Javascript indeed is very popular, but the language is still missing the power of Array processing as provided by APL. Is it possible to use the work you have done as a Class within ES2015?

**Comment by ngn** [comment]
I'm not familiar with ES2015 but a quick search tells me a "class" is nothing but syntax sugar for a JS function with a prototype.  So, I'm not sure I understand your question.
