### ISSUE TITLE
Platform independent build?

### ISSUE THREAD

**Issue by eprozium** [ngn/apl#97]
Hi,

Could you please add a platform independent build? E.g. with Grunt or Gulp?

Thank you.

**Comment by ngn** [comment]
I'm afraid I don't know how to use Grunt or Gulp.  Bash works on all platforms I care about, and for Windows I guess something like cygwin can provide a sane shell-like environment.

**Comment by eprozium** [comment]
> I'm afraid I don't know how to use Grunt or Gulp.

Than let the community do it :).

But considering the level of difficulty and complexity your JS implementation of APL has, one can't possibly believe that you don't grasp those tools in a few minutes :).

> Bash works on all platforms I care about, and for Windows I guess something like cygwin can provide a sane shell-like environment.

Your bash script contains hardcoded paths that exist only on Linux.
Having cross-platform build ensures that the community will be able to help easier.

**Comment by ngn** [comment]
> Than let the community do it :).

I'd be happy to accept a pull request, if you think this is important :)
I'm not pretending - I really don't know how to use these build frameworks.  I never felt the need for them.

> But considering the level of difficulty and complexity your JS implementation of APL has, one can't possibly believe that you don't grasp those tools in a few minutes :).

Complex code is not a sign of great learning skill.  Quite the opposite.

> Your bash script contains hardcoded paths that exist only on Linux.

Really?  The only hard-coded path I can see is here:
```bash
   echo '//usr/bin/env node "$0" $@;exit $?' >$f
```
This generates the first line of `lib/apl.js` which is a comment as far as JavaScript is concerned.

**Comment by eprozium** [comment]
> I never felt the need for them.

Sorry, for not trying to push something you don't need on your project.

Having a standard build tool (that is also understood by IDEs) instead of self made scripts tend to make life easier usually, especially for others.

> Complex code is not a sign of great learning skill. 

No, but solving a complex problem usually is :) .

> The only hard-coded path I can see is here ...

Sorry, I only saw that it's broken on Windows and I assumed the paths are the problem ( most of the time really is :) ).
