### ISSUE TITLE
'?' zero based?

### ISSUE THREAD

**Issue by eprozium** [ngn/apl#98]
'?' seems to be zero based as opposed to other APL implementations :(

**Comment by ngn** [comment]
Traditionally in APL `?` as well as a few other primitives have been dependent on a special variable called [`⎕IO`](http://help.dyalog.com/15.0/Content/Language/System%20Functions/io.htm) (for "index origin", pronounced /kwɒd.ʌɪ.əʊ/). With `⎕IO←0` the returned values `R←?N` are `(0≤R) ∧ R<N` and with `⎕IO←1` - `(0<R) ∧ R≤N`. This also affects iota (`⍳3` is `0 1 2` or `1 2 3`), indexing (the `B` in `A[B]`, `B⊃A`, `B⌷A`), axis specification (`K` in `A ⌽[K] B`) and more.  On the other hand, residue (`|`), encode (`⊤`), decode (`⊥`), the left argument for trig fns (`A○B`) remain unaffected, and booleans are always `0 1`.

Leaving this choice of index origin to the user lead to a "holy war" with different implementations opting for different defaults. The majority preferred `⎕IO←1`. However, in J and K, which are descendants of APL, the index origin is fixed at 0 and not configurable.

Advocates of `⎕IO←1` point out that we say "first-second-third" when we count, and that mathematical notation is usually 1-based.  Proponents of `⎕IO←0` point out that in programming we want "indices" to be the same as "offsets" from the beginning of the array, and that sometimes in mathematics 0...N-1 is more natural (e.g. residues).

I think leaving this ambiguity in APL was the single worst mistake in its design. I also find the arguments for `⎕IO←0` much more convincing, so in ngn/apl I took a side and decided to allow only 0. This also made the implementation easier, JavaScript being a 0-based language.

**Comment by eprozium** [comment]
Thank you for clarifying this.

The problem is that having:
```DOMAIN ERROR: The index origin (⎕IO) is fixed at 0```
many existing examples won't work, so NGN-APL can't be used as a simple browser based drop in replacement for tutorials/demos :( .

**Comment by ngn** [comment]
For many of the examples in the wild it won't work, sorry :( But it's never terribly hard to make code work with `⎕IO←0`.
